Criação do Service, Mapper e Tests de Usuário e Contato
academiadev-jlle/backend-thunderpets pull request #28
Opened 2018-11-10 02:55 UTC by nefasta

* Criação da classe UsuarioService: organização das regras de negócio no UsuarioService afim de atender o padrão do Spring MVC.
* Criação das classes UsuarioMapper e ContatoMapper: as classes visam fazer o mapeamento dos atributos entre entidade e DTO, e vice e versa. Para tal é utilizado o gerador de código MapStruct.
* Alteração da classe UsuarioControllerTests: foram desenvolvidos possíveis cenários de utilização do Controller de Usuário.
* Criação da classe Util: centralizar métodos utilitários.

2018-11-12 19:16 UTC, rartner requested changes

2018-11-12 19:16 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
> +    private UsuarioMapper usuarioMapper;
Eu, particularmente, acho meio estranho dar autowire numa classe abstrata, visto que classes abstratas não podem ser instanciadas. Eu preferiria que os mappers fossem declarados como interfaces e que fossem utilizadas as anotações do MapStruct pra fazer o mapeamento dos campos.

2018-11-12 19:16 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/mapper/UsuarioMapper.java
> +    void setContato(Usuario usuario, @MappingTarget UsuarioDTO usuarioDTO) {
```
  @Mappings({
            @Mapping(source = "usuario.createdAt", target = "created_at", dateFormat = "dd/MM/yyyy HH:mm"),
            @Mapping(source = "saldo.total", target = "saldo.total", numberFormat = "#,##0.00"),
            @Mapping(source = "saldo.pagar", target = "saldo.pagar", numberFormat = "#,##0.00"),
            @Mapping(source = "saldo.receber", target = "saldo.receber", numberFormat = "#,##0.00"),
    })
    UsuarioGetResponseDTO toUsuarioComSaldo(Usuario usuario, Saldo saldo);
```

A gente tinha conversado sobre como fazer só com as annotations, talvez isso ajude

2018-11-12 19:16 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
> +        Usuario usuario = usuarioRepository.findById(id).get();
dá pra fazer usando um 
```
Usuario usuario = usuarioRepository.findById(id).orElseThrow(() -> new UsuarioNaoEncontradoException());
```
Acho que fica mais bonitinho, não precisa do if ali em cima.

2018-11-12 19:16 UTC, rartner commented on src/test/java/br/com/academiadev/thunderpets/controller/UsuarioControllerTests.java
> +public class UsuarioControllerTests {
Ainda não consegui rodar os testes aqui :( assim que der eu atualizo o review. Mas passou no CI, então deve estar sucesso

2018-11-12 19:16 UTC, rartner commented on src/test/java/br/com/academiadev/thunderpets/mapper/ContatoMapperTests.java
> +
Consegue fazer testes pros métodos que retornam listas também? Acho interessante cobrir isso porque imagino que a gente vá usar bastante

2018-11-12 19:23 UTC, rartner requested changes

2018-11-17 18:54 UTC, nefasta commented on src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
> +    private UsuarioMapper usuarioMapper;
Então, eu estava fazendo de um jeito complicado hehehe. Mas agora acabei entendendo melhor o funcionamento do MapStruct alterei os mappers e declarei eles como interfaces. :)

2018-11-19 09:44 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/service/UsuarioService.java
> +    private UsuarioMapper usuarioMapper;
Bom trabalho, miga. Vou testar tudo mais tarde, mas parece ok :flight_departure:

2018-11-21 00:49 UTC, rartner approved these changes
Encontrei um probleminha ali testando manualmente, mas é coisa das exceções, então pode deixar que eu corrijo isso ainda nessa sprint :smiley: 
Desculpa a demora no review. Não esquece de atualizar tua branch com a release/3. Bom trabalho, miga.

2018-11-22 15:16 UTC, merged