Refatorações
academiadev-jlle/backend-thunderpets pull request #39
Opened 2018-11-24 22:16 UTC by rartner

Esse PR traz as modificações solicitadas em algumas issues:

* Refatoração para permitir usuários sem contatos e deixar o e-mail como único (#35)
* Adição de um `ControllerAdvice` para tratamento das exceções do sistema, visando facilitar o trabalho dos meninos do frontend na identificação de erros (#31)
* Refatoração do processo de busca, listagem e inserção de pets, visando deixá-los de acordo com as necessidades do frontend. Os pontos alterados estão melhores destacados aqui: #34 

Qualquer dúvida é só chamar

2018-11-26 16:03 UTC, nefasta commented
Eu vi que colocastes o `@Column(unique = true)` lá no model do usuário, mas também precisaria colocar nos scripts do flyway, lá no V0001__criacao_tabela_usuario.sql. Testei colocando o script `CONSTRAINT email_uk UNIQUE (email)` e funcionou de boinhas.

2018-11-26 16:03 UTC, helenadalmazo reviewed
Eu vi que colocastes o `@Column(unique = true)` lá no model do usuário, mas também precisaria colocar nos scripts do flyway, lá no V0001__criacao_tabela_usuario.sql. Testei colocando o script `CONSTRAINT email_uk UNIQUE (email)` e funcionou de boinhas.

2018-11-26 17:16 UTC, helenadalmazo reviewed
Acho que daria para colocar um `@Size(min = 8, max = 99)` no model do usuário, porque se testar criando um usuário com nomes menores do que o permitido aparece a mensagem "tipo tamanho deve estar entre 3 e 2147483647". Só que nossa tabela de usuário tem um datatype de `varchar(99)`.

2018-11-26 17:18 UTC, nefasta commented on src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
> +                .orElseThrow(() -> new PetNaoEncontradoException(String.format("Pet %s não encontrado", id.toString())));
Que exception chique 😁

2018-11-26 20:51 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/service/impl/UsuarioServiceImpl.java
> +            throw new ErroAoProcessarException("O usuário precisa ter pelo menos um contato cadastrado.");
Sorry, jurava que tinha tirado isso. Corrigido!

2018-11-26 20:52 UTC, rartner commented on src/test/java/br/com/academiadev/thunderpets/controller/UsuarioControllerTests.java
> +        usuarioNaoEncontrado.andExpect(status().is(404))
Não percebi isso. Corrigido!

2018-11-26 20:52 UTC, rartner commented on src/test/java/br/com/academiadev/thunderpets/controller/UsuarioControllerTests.java
> +        deleteUsuarioNaoEncontrado.andExpect(status().is(404))
Teje corrigido

2018-11-26 20:58 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
> +                .orElseThrow(() -> new PetNaoEncontradoException(String.format("Pet %s não encontrado", id.toString())));
O cara lá de cima disse "faça o código bonitinho que os elogios virão até você" :point_up:

2018-11-27 20:13 UTC, diogoantelo commented on src/main/java/br/com/academiadev/thunderpets/controller/PetController.java
> +                .orElseThrow(() -> new PetNaoEncontradoException(String.format("Pet %s não encontrado", id.toString())));
O pessoal do front vem por meio desteagradecer do fundo do coração por seus esforços

2018-11-27 20:21 UTC, diogoantelo requested changes

2018-11-27 20:21 UTC, diogoantelo commented on src/main/java/br/com/academiadev/thunderpets/model/Pet.java
>      @Column(columnDefinition = "bool default true")
Acredito que não precise colocar o columnDefinition se você usou o "ativo = true".

2018-11-27 20:31 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/model/Pet.java
>      @Column(columnDefinition = "bool default true")
Teje removido

2018-11-28 09:57 UTC, diogoantelo approved these changes

2018-11-28 10:08 UTC, merged