Inclusão de uma entidade auditável
academiadev-jlle/backend-thunderpets pull request #45
Opened 2018-12-05 00:15 UTC by LiserLine

O que foi feito:
Inclusão de uma entidade auditável.
Utilização da auditoria na _dataRegistro_ do Pet

**Classe auditável adicionada.**
Agora é possível saber quando a entidade foi criada.

**Configurações para implementação adicionadas**
Auditoria começa quando a aplicação inicia.
Links de auditoria para as classes que a utilizam

2018-12-05 11:31 UTC, nefasta commented on src/test/java/br/com/academiadev/thunderpets/controller/PetControllerTest.java
> +//                .andExpect(jsonPath("$.content[0].localizacao.descricao", is("R. Dona Francisca - Centro, Joinville - SC, 89201-070")))
Esse teste aqui a princípio passou no último [build](https://circleci.com/gh/academiadev-jlle/backend-thunderpets/184?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) do CircleCI, acho que dá para descomentar essas linhas que não haverá problemas. 😁

2018-12-05 11:39 UTC, nefasta commented on src/test/java/br/com/academiadev/thunderpets/controller/PetControllerTest.java
> +//                .andExpect(jsonPath("$.content[0].nome", is("Pocotó")))
O teste falhou porque a busca por Pets por padrão é feita por dataRegistro DESC, conforme `PetController`:

> @ApiParam(value = "Direção da ordenação: ascendente ou descendente")
  @RequestParam(defaultValue = "DESC") Sort.Direction direcao,
@ApiParam(value = "Nome da coluna que será usada para a ordenação")
  @RequestParam(defaultValue = "dataRegistro") String campoOrdenacao,

E, quando eu criei os testes eu adicionei valores fixos ao atributo dataRegistro, conforme `PetDTOUtil`:

> .nome("Carijó")
.dataRegistro(LocalDate.of(2018, 8,4))

> .nome("Pocotó")
.dataRegistro(LocalDate.of(2018, 12,1))

Desculpeee, não havia lembrado da auditoria dos pets quando fiz os testes. My bad 😐

Mas entãooo, acho que dá pra remover esse atributo lá do builder, igual você fez nas classes `PetMapperTest` e `PetUtil`. Logo, como no teste em questão o pet Carijó é criado antes, é só inverter. Dá pra criar o pet Pocotó antes ou inverter os índices dos `jsonPath` esperados.

2018-12-06 00:33 UTC, rartner requested changes

2018-12-06 00:33 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/config/audit/SpringSecurityAuditorAware.java
> +public class SpringSecurityAuditorAware implements AuditorAware<String> {
Por que precisa dessa classe? Não lembro da gente utilizando isso nos exemplos

2018-12-06 00:33 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/model/EntidadeAuditavel.java
> +    private LocalDate dataRegistro;
Tava pensando aqui, talvez seja melhor colocar um LocalDateTime. Vai ajudar na hora da ordenação e tal

2018-12-06 00:33 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/model/Pet.java
> +    public Pet(LocalDate dataRegistro, String nome, @NotNull String descricao, LocalDate dataAchado, @NotNull Especie especie, @NotNull Porte porte, @NotNull Sexo sexo, @NotNull Status status, @NotNu
Nunca vi um construtor com o `@Builder`. Pra quê serve?

2018-12-06 00:33 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
> +    @Builder.Default
Pra quê serve isso, migo?

2018-12-06 00:33 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
>                  throw new ErroAoProcessarException("Para buscas por raio de distância é necessário informar a lagitude e longitude do usuário atual.");
Não foi você que alterou, mas tá escrito `lagitude`. Consegue arrumar pra gente? :heart:

2018-12-06 00:41 UTC, LiserLine commented on src/main/java/br/com/academiadev/thunderpets/config/audit/SpringSecurityAuditorAware.java
> +public class SpringSecurityAuditorAware implements AuditorAware<String> {
Eu coloquei nos primeiros testes... Isso servia pra pegar o cara que estava atualizando aquela entidade. Servia basicamente pra atribuir a prop. createdBy/updatedBy.
**Removido**

2018-12-06 00:46 UTC, LiserLine commented on src/main/java/br/com/academiadev/thunderpets/model/EntidadeAuditavel.java
> +    private LocalDate dataRegistro;
Colocado!

2018-12-06 00:48 UTC, LiserLine commented on src/main/java/br/com/academiadev/thunderpets/model/Pet.java
> +    public Pet(LocalDate dataRegistro, String nome, @NotNull String descricao, LocalDate dataAchado, @NotNull Especie especie, @NotNull Porte porte, @NotNull Sexo sexo, @NotNull Status status, @NotNu
Se colocado o @Builder na classe filho e na classe pai o método builder() não funciona, pois ele não consegue encontrar a variável do pai. Uma das formas é colocar o construtor na classe filho colocando o @Builder na mesma e chamando a variável do pai com o super(). A outra forma é utilizar o @SuperBuilder, porém eu não consegui com que funcionasse.

2018-12-06 00:50 UTC, LiserLine commented on src/main/java/br/com/academiadev/thunderpets/model/Usuario.java
> +    @Builder.Default
O log dava um _warning_ dizendo que se não colocar a anotação o valor padrão que foi atribuido não iria ser utilizado, deixando a prop. sem valor default.

2018-12-06 00:52 UTC, LiserLine commented on src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
>                  throw new ErroAoProcessarException("Para buscas por raio de distância é necessário informar a lagitude e longitude do usuário atual.");
👍

2018-12-06 19:58 UTC, nefasta commented on src/main/java/br/com/academiadev/thunderpets/service/impl/PetServiceImpl.java
>                  throw new ErroAoProcessarException("Para buscas por raio de distância é necessário informar a lagitude e longitude do usuário atual.");
Ops, hehehehe. Lagitude e longitude!

2018-12-09 05:43 UTC, rartner approved these changes

2018-12-09 05:43 UTC, merged