Esqueci minha senha e redefinição de senha (#40)
academiadev-jlle/backend-thunderpets pull request #46
Opened 2018-12-05 18:03 UTC by nefasta

**O que foi feito**
* Inclusão de endpoint `esqueci-minha-senha`, para que os usuários possam solicitar a redefinição de senha. Tal serviço é responsável por enviar um e-mail com o link de redefinição para endereço do usuário. Dessa maneira o usuário pode efetuar a redefinição.
* Inclusão de endpoint `redefinir-senha` que irá alterar a senha o usuário.

2018-12-05 21:04 UTC, rartner requested changes

2018-12-05 21:04 UTC, rartner commented on src/main/java/br/com/academiadev/thunderpets/service/impl/EmailServiceImpl.java
> +            return "Erro ao enviar e-mail: " + e.getMessage();
Ele não dá nenhuma exception mais específica pra gente tratar?

2018-12-05 21:04 UTC, rartner commented on src/main/resources/application.yml
> +    password: visaoalemdoalcance
Acho que não é legal o pessoal saber da nossa senha eiuheueh coloca numa variável de ambiente, porfa

2018-12-05 21:09 UTC, damews reviewed
Os [...]NãoEncontradoException foram pro limbo?

2018-12-06 20:34 UTC, nefasta commented on src/main/resources/application.yml
> +    password: visaoalemdoalcance
Eu não sabia exatamente se dava pra fazer nem como fazia, hehehehe. Thaaaanks! 😁

2018-12-06 20:34 UTC, nefasta commented on src/main/java/br/com/academiadev/thunderpets/service/impl/EmailServiceImpl.java
> +            return "Erro ao enviar e-mail: " + e.getMessage();
Ops, sorry, alterado para `MailException`.

2018-12-06 20:35 UTC, nefasta commented on src/main/java/br/com/academiadev/thunderpets/model/Pet.java
> +    @NotNull
Conversei com o frontend (@diogoantelo) e a call foi deixar o `@NotNull`

2018-12-07 12:33 UTC, rartner approved these changes
:rocket:

2018-12-07 15:58 UTC, merged